name: Visit Netlify Bi-Monthly
on:
  schedule:
    - cron: '0 0 1 * *'
    - cron: '0 0 15 * *'
  workflow_dispatch:

jobs:
  visit-sites:
    runs-on: ubuntu-latest
    steps:
      - name: Visit Netlify sites
        run: |
          curl -s "https://spa53.netlify.app/"
          echo "✅ Sitio Netlify visitado automáticamente"

          
          
